### ISSUE TITLE
USER STORY: Home page access

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#1]
EPIC: Home page access

As an **user** I can **access the home page event ** so that ** I can see general information about the wedding**.

### Acceptance Criteria:

The user must be able to acces the home page with the date, the town location and the theme of the wedding.

### Tasks:

- [x] Design the home page
- [x] Implement Django
- [x] Create the base.py and the index.py for the home page
- [x] Create the HTML structure and CSS of the home page
