### ISSUE TITLE
USER STORY: Memories Page view

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#12]
EPIC: Picture Page view

As **an admin or guest**, I can **access the Memories page** so that **I can view the Memories with pictures taken during the event or comments guest or admin would have add**.

### Acceptance Criteria:

The Memories page could be visible only to authenticate admin and guest.

### Tasks:

- [x] design the Memories page
- [x] create django template for Memories page with html and css
- [x] set up django-allauth functinality to the Memories page
- [x] only users that are login can see this page
