### ISSUE TITLE
USER STORY: Memories Page participation

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#13]
EPIC:  Picture Page participation

As **a guest or admin**, I can **send memories from the Memories page** so that **I can share comments or pictures I took during the weeding**.

### Acceptance Criteria:

The guest or admin can send a form with comments or pictures in the Memories page.

### Tasks:

- [x] set up a form button in the Memories page
- [x] the button should redirect to a form page
- [x] add edit/delete button for user memories
- [x] add info validation
