### ISSUE TITLE
USER STORY: Accessibility

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#15]
EPIC: Accessibility

As **a blind user**, I can **access website information** so that **I can prepare for the weeding**.

### Acceptance Criteria:

The user can easily navigate the website thanks to accessibility code standard.

### Tasks:

- [x] links have aria-label attributes
- [x] pictures have alt attributes 
- [x] buttons have aria-label attributes
- [x] the html pages have a good semantic and layout
