### ISSUE TITLE
USER STORY: Memories filter

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#16]
EPIC: Memory Page filter

As an **guest or admin** I can **select categories in the Memory Page** so that **I can filter the memory's posts**.

### Acceptance Criteria:

The guest and admin can access settings to filter the memories.

### Tasks:

- [x] update database to include location, people and bride/groom/both guest.
- [x] update the views to add the filter for the location and bride/groom/both guest.
- [x] update the html and css of memories.html.
