### ISSUE TITLE
USER STORY: Alert Messages

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#17]
EPIC: Alert Messages

As an **guest or admin** I can **see alert messages** so that **it confirms the action I took**.

### Acceptance Criteria:

A message appears when a memory post is added, edited or deleted.

### Tasks:

- [x] use Bootstrap and JavaScript to create the alert.
- [x] add django message functionnality 
- [x] create the html
