### ISSUE TITLE
USER STORY: Guest List credential

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#5]
EPIC: Guest List credential

As **an admin**, I can **create username for a guest**so that **guests can sign up and access their guest page using this username**.

### Acceptance Criteria:

The admin could create a guest username when creating a guest or from the guest list.

### Tasks:

- [x] create the functionality for the admin to create the guest username using PostgreSQL during guest creation
- [x] create the functionality for the admin to create the guest username using PostgreSQL from guest list
- [x] add information validation and error handling (no username duplicate)
