### ISSUE TITLE
USER STORY: Guest List management

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#6]
EPIC: Guest List management

As **an admin**, I can **manage the guest list** so that I can **add edit or delete a guest** .

### Acceptance Criteria:

The admin should be able to manage guest details from the guest list.

### Tasks:

- [x] create the functionality for the admin to create the guest username using P
- [x] create functionality for admin to edit guest details using PostgreSQL                                                                   
- [x] create functionality for admin to delete guest for guest list using PostgreSQL
- [x] add information validation and error handling
