### ISSUE TITLE
USER STORY: Guest Sign In

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#7]
EPIC: Guest Sign In

As **a guest**, I can **sign in** so that **I can access more detailed information about the wedding**

### Acceptance Criteria:

A register guest should be able to sign in with his username and password.

### Tasks:

- [x] install django-allauth 
- [x] add sign in guest option to the home page 
- [x] add code sign in functionality and error handling
