### ISSUE TITLE
USER STORY: Guest Page

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/the-W-invitation#8]
EPIC: Guest Page

As **a guest**, I can **edit or delete my details** so that **I can manage my details from my guest page**

### Acceptance Criteria:

The guest could access its own page and edit or delete his guest access.

### Tasks:

- [ ] design and create a guest details page (HTML and CSS)
- [ ] create guest edit guest details functionality  using PostgreSQL
- [ ] create guest delete guest functionality PostgreSQL 
- [ ] prevent guest to edit the username
- [ ] add message validation and/or error handling
